[build]
  command = "npm cache clean --force && npm ci && npm rebuild && gatsby clean && gatsby build"
  publish = "public"

[context.production.environment]
  NODE_ENV = "production"
  GO_VERSION = "1.19" 